# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "ooga04/amzn2"
  config.vm.box_version = "2.0.20190228"
  config.vm.network "private_network", ip: "192.168.240.11"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.cpus = "1"
  end

  config.vm.provision :shell, :inline => <<-EOT
    sudo amazon-linux-extras install -y ansible2
    sudo ansible-playbook /vagrant/local-site.yml
  EOT

  config.vm.provision :shell, run: "always", :inline => <<-EOT
    sudo docker-compose -f /vagrant/docker-compose.yml up -d
  EOT

end
